[project]
name = "GlassesDet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "albumentations>=2.0.8",
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "opencv-python>=5.0.0.93",
    "pandas>=2.3.3",
    "pillow>=12.3.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
    "ultralytics>=8.4.123",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu126", marker = "sys_platform == 'win32' or sys_platform == 'linux'" }]
torchvision = [{ index = "pytorch-cu126", marker = "sys_platform == 'win32' or sys_platform == 'linux'" }]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
